# Generated by Django 5.2 on 2026-04-26 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_mode', models.CharField(max_length=50)),
                ('order_region', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(max_length=50)),
                ('customer_segment', models.CharField(max_length=50)),
                ('scheduled_days', models.IntegerField(default=3)),
                ('actual_duration', models.IntegerField(default=3)),
                ('order_hour', models.IntegerField(default=10)),
                ('order_day_of_week', models.IntegerField(default=2)),
                ('predicted_risk', models.FloatField(default=0.0)),
                ('predicted_class', models.CharField(max_length=20)),
                ('actual_status', models.CharField(choices=[('PENDING', 'Pending'), ('LATE', 'Late'), ('ON_TIME', 'On-Time')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_en', models.TextField()),
                ('message_ar', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.shipment')),
            ],
        ),
    ]
