# Generated by Django 5.2 on 2026-04-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delayreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='delayreport',
            name='reporter_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='delayreport',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
